import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

export async function extractPdf(
  path: string,
): Promise<{ data: unknown } | { message: string }> {
  const { extractData } = await import('@formepdf/core');

  const resolved = resolve(path);
  const bytes = await readFile(resolved);
  const data = extractData(new Uint8Array(bytes));

  if (data === null) {
    return {
      message:
        'No embedded Forme data found in this PDF. It may not have been generated by Forme, or was generated before embedded data support was added.',
    };
  }
  return { data };
}
